version: '3.4'
services:    
  consumer:
    build: .
    container_name: consumer
    command: yarn dev
    environment:
      REDIS_HOST: 'rediscache'
      REDIS_PORT: '6379'
      REDIS_USER: 'redis_user'
      MONGO_URI: 'mongodb://mongodb:27017/Medical'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - .:/app
    networks: 
      - socket-server_common

networks:
  socket-server_common:
    external: true
